### ISSUE TITLE
Extend support back to Ruby 2.2

### ISSUE THREAD

**Issue by alexgenco** [kana/vim-flavor#54]
I'd like to use vim-flavor 3.0.0 for the neovim-ruby test suite, but I can't because it requires `~> 2.5` , and neovim-ruby is supported/tested against Ruby versions back to 2.2 (the earliest currently-maintained ruby version). It looks like the vim-flavor test suite passes on 2.2.1, so I'm wondering if there's a particular reason not to support it? Thanks!

**Comment by kana** [comment]
Support for older versions will be terminated soon than newer versions. That’s why I chose the newest version of Ruby as updating major version of vim-flavor.

And, according to https://www.ruby-lang.org/en/downloads/branches/, support for Ruby 2.2 is already terminated (or will be terminated soon).

**Comment by alexgenco** [comment]
Ok that's fine, just thought I'd ask :)
